### ISSUE TITLE
unable to read csi driver mounted file

### ISSUE THREAD

**Issue by raffaelespazzoli** [spiffe/spiffe-csi#54]
I installed this csi driver in OpenShift and it does not work. I can see the unix socket mounted in the container, but I get this error:

```
drwxr-xr-x.   2 root root   60 Oct 29 20:28 spiffe-workload-api
drwxr-xr-x.   2 root root    6 Jun 21  2021 srv
dr-xr-xr-x.  13 root root    0 Oct 29 19:14 sys
drwxrwxrwx.   2 root root   58 Oct 26 11:23 tmp
drwxr-xr-x.  12 root root  144 Oct 26 11:09 usr
drwxr-xr-x.  19 root root  249 Oct 26 11:09 var
sh-4.4$ ls -la spiffe-workload-api
ls: cannot open directory 'spiffe-workload-api': Permission denied
sh-4.4$ id
uid=1000690000(1000690000) gid=0(root) groups=0(root),1000690000
```
as you can see, based on the group, I should be able to ls that directory. I suspect selinux might be in play here. Any suggestions?

also this is failing:
```
/opt/spire $ /opt/spire/bin/spire-agent api fetch -socketPath $SPIFFE_ENDPOINT_SOCKET
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /opt/spire/unix:/spiffe-workload-api/spire-agent.sock: connect: no such file or directory"
```
see also https://github.com/spiffe/spire-tutorials/issues/95

**Comment by raffaelespazzoli** [comment]
@azdagron my deployment meets your requirements:
```
        - name: spiffe-csi-driver
          image: ghcr.io/spiffe/spiffe-csi-driver:nightly
```
and:
```
        volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true                        
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true  
```

**Comment by raffaelespazzoli** [comment]
I found proof that selinux is denying access
```
time->Fri Nov  4 17:52:55 2022
type=PROCTITLE msg=audit(1667584375.484:68): proctitle=6C73002D6C61002F7370696666652D776F726B6C6F61642D617069
type=SYSCALL msg=audit(1667584375.484:68): arch=c000003e syscall=2 success=no exit=-13 a0=7ffedde6edda a1=98000 a2=0 a3=0 items=0 ppid=266580 pid=266767 auid=4294967295 uid=1000680000 gid=0 euid=1000680000 suid=1000680000 fsuid=1000680000 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm="ls" exe="/bin/busybox" subj=system_u:system_r:container_t:s0:c15,c26 key=(null)
type=AVC msg=audit(1667584375.484:68): avc:  denied  { read } for  pid=266767 comm="ls" name="agent-sockets" dev="tmpfs" ino=1257099 scontext=system_u:system_r:container_t:s0:c15,c26 tcontext=system_u:object_r:container_var_run_t:s0 tclass=dir permissive=0
```

**Comment by azdagron** [comment]
I don't have any experience running the CSI driver in OpenShift. Perhaps @bendikp or @erikgb have some insight into SELinux policies in OpenShift that might impact this (they previously filed issue #42 related to failures in Openshift due to SELinux).

**Comment by erikgb** [comment]
@azdagron Thanks for the ping! I was supposed to follow up on this, but had a lot of other things to do lately. 😅 It turns out that this is not something specific to Openshift, as I was able to reproduce the same problem in Rancher RKE2 if I enable SELinux. And I wonder if something can be done to mend this in the Spiffe CSI driver? 🤔 I suspect it to be related to the fact that we now mount the socket with read-write, but enforce the user to configure it as read-only. But I am mainly a developer, and not a sysadmin, and I also have limited experience with SELinux (except frustrations about non-working stuff). 😉 

In the meantime, I managed to work around this problem (on RKE2) by installing https://github.com/kubernetes-sigs/security-profiles-operator, and ensuring the workloads that tries to mount the socket using Spiffe CSI, have the following resource bound:

````
apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
spec:
  allow:
    container_var_run_t:
      sock_file:
      - write
  inherit:
  - kind: System
    name: container
````

We were supposed to try a similar approach on our Openshift clusters, but I think other tasks came in the way. Maybe @bendikp has something to add?
